myflask/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from myflask import db


class User(db.Model, UserMixin):
    __table__ = db.Model.metadata.tables['user']

    '''
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(25), nullable=False)
    last_name = db.Column(db.String(25), nullable=False)
    DOB = db.Column(db.Date, nullable=False)
    email = db.Column(db.Text, unique=True, nullable=False)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(25), nullable=False)
    user_type = db.Column(db.Text, nullable=False)
    country = db.Column(db.Text, nullable=False)
    profile_pic = db.Column(db.String, nullable=False)
    '''

    def __repr__(self):
        return f"{self.id} {self.first_name} {self.last_name} {self.DOB} {self.email} {self.username} {self.password} \
        {self.country} {self.user_type}"

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

myflask/__init__.py
from flask import Flask
from flask_login import LoginManager, login_required
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect

db = SQLAlchemy()
login_manager = LoginManager()
csrf = CSRFProtect()
csrf.exempt_views.add('dash.dash.dispatch')


def _protect_dash_views(dash_app):
    for view_func in dash_app.server.view_functions:
        if view_func.startswith(dash_app.config.routes_pathname_prefix):
            dash_app.server.view_functions[view_func] = login_required(dash_app.server.view_functions[view_func])


def register_dash_apps(app):
    with app.app_context():
        from mydash.layoutindex import DashAppIndex
        dash_app_index = DashAppIndex(app)
        dash_app_index.setup()
        _protect_dash_views(dash_app_index.app)

        from mydash.layout1 import DashApp1
        dash_app1 = DashApp1(app)
        dash_app1.setup()
        _protect_dash_views(dash_app1.app)

        from mydash.layout2 import DashApp2
        dash_app2 = DashApp2(app)
        dash_app2.setup()
        _protect_dash_views(dash_app2.app)

        from mydash.layout3 import DashApp3
        dash_app3 = DashApp3(app)
        dash_app3.setup()
        _protect_dash_views(dash_app3.app)

        from mydash.layout4 import DashApp4
        dash_app4 = DashApp4(app)
        dash_app4.setup()
        _protect_dash_views(dash_app4.app)


def create_app(config_class_name):
    app = Flask(__name__)
    app.config.from_object(config_class_name)

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = "auth.login"
    csrf.init_app(app)

    register_dash_apps(app)

    with app.app_context():
        # from myflask.models import User
        db.Model.metadata.reflect(bind=db.engine)
        # db.create_all()

    from myflask.auth.routes import auth_bp
    app.register_blueprint(auth_bp)

    from myflask.main.routes import main_bp
    app.register_blueprint(main_bp)

    return app

myflask/app.py
from myflask import create_app
from myflask.config import DevelopmentConfig

app = create_app(DevelopmentConfig)

if __name__ == '__main__':
    app.run(debug=True)

myflask/main/routes.py
from flask import Blueprint, redirect, url_for
from flask import render_template
from flask_login import login_required, UserMixin, current_user

main_bp = Blueprint('main', __name__, url_prefix='/')


@main_bp.route('/')
def welcome():
    if current_user.is_anonymous:
        return render_template('welcome.html', title="Welcome")
    return redirect(url_for('main.index'))


@main_bp.route('/home')
@login_required
def index():
    return render_template('index.html', title="Home")


@main_bp.route('/data/eruption_numbers')
@login_required
def eruption_numbers():
    return render_template('eruption_numbers.html', title="Number of Volcanic Eruptions")


@main_bp.route('/data/yearly_data')
@login_required
def yearly_data():
    return render_template('yearly_data.html', title="Yearly Data")


@main_bp.route('/data/for_countries')
@login_required
def for_countries():
    return render_template('for_countries.html', title="Data for Countries")


@main_bp.route('/data/population')
@login_required
def population():
    return render_template('population.html', title="Population Risk")


@main_bp.route('/dash_app_index')
@login_required
def dash_app_index():
    return redirect('/dash_app_index/')


@main_bp.route('/dash_app1')
@login_required
def dash_app1():
    return redirect('/dash_app1/')


@main_bp.route('/dash_app2')
@login_required
def dash_app2():
    return redirect('/dash_app2/')


@main_bp.route('/dash_app3')
@login_required
def dash_app3():
    return redirect('/dash_app3/')


@main_bp.route('/dash_app4')
@login_required
def dash_app4():
    return redirect('/dash_app4/')

myflask/templates/_formhelpers.html
{% macro render_field(field) %}

    <div class="input-group responsive m-b-30">
        {{ field.label }}
        <div class="input">
            {{ field() }}
        </div>
    </div>

    {% if field.errors %}

        <div class="input-group responsive m-b-30">

            <label class="is-red-500">
                {% for error in field.errors %}
                    *{{ error }}
                {% endfor %}
            </label>

        </div>

    {% endif %}
{% endmacro %}

myflask/templates/admin.html
{% extends "layout.html" %}
{% from "_formhelpers.html" import render_field %}
{% set page_name = 'admin' %}

{% block content %}
    {% include 'flashmessages.html' %}

    <div class="flex h-minus-nav">

        {% include 'sidebar_admin.html' %}

        <div class="container">
            <br>
            <h1 style="text-align: center">User Management</h1>
            <br>
            <table class="table">


                <thead>
                <tr>
                    <th></th>
                    <th class="is-bold">Username</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Date of Birth</th>
                    <th>Country</th>
                    <th class="is-center">Delete</th>
                </tr>
                </thead>


                <tbody>
                {% for eachuser in userlist %}
                    <tr>
                        {% if eachuser.user_type == 'admin' %}
                            <td class="is-center"
                            ><a><span class="d-icon d-security-verified-solid is-green-600"></span></a
                            ></td>
                        {% else %}
                            <td></td>
                        {% endif %}

                        <td><a href="/user/{{ eachuser.username }}">{{ eachuser.username }}</a></td>
                        <td>{{ eachuser.first_name }} {{ eachuser.last_name }}</td>
                        <td>{{ eachuser.email }}</td>
                        <td class="is-mono">{{ eachuser.DOB }}</td>
                        <td>{{ eachuser.country }}</td>
                        {% if eachuser.user_type == 'admin' %}
                            <td></td>
                        {% else %}
                            <td class="is-center">
                                <a href="/user/{{ eachuser.username }}/delete">
                                    <span class="d-icon d-trash is-small is-red-500"></span>
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>


            </table>
        </div>


    </div>

{% endblock %}

myflask/templates/admin_requests.html
{% extends "layout.html" %}
{% from "_formhelpers.html" import render_field %}
{% set page_name = 'admin_requests' %}
{% block content %}
    {% include 'flashmessages.html' %}
    <div class="flex h-minus-nav">
        {% include 'sidebar_admin.html' %}
        <div class="container">
            <br>
            <h1 style="text-align: center">Requests to Become an Administrator</h1>
            <br>
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th class="is-bold">Username</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Date of Birth</th>
                    <th>Country</th>
                    <th class="is-center">Approve</th>
                    <th class="is-center">Reject</th>
                </tr>
                </thead>
                <tbody>
                {% for eachuser in userlist %}
                    <tr>
                        {% if eachuser.user_type == 'admin' %}
                            <td class="is-center"
                            ><a><span class="d-icon d-security-verified-solid is-green-600"></span></a
                            ></td>
                        {% else %}
                            <td></td>
                        {% endif %}

                        <td><a href="/user/{{ eachuser.username }}">{{ eachuser.username }}</a></td>
                        <td>{{ eachuser.first_name }} {{ eachuser.last_name }}</td>
                        <td>{{ eachuser.email }}</td>
                        <td class="is-mono">{{ eachuser.DOB }}</td>
                        <td>{{ eachuser.country }}</td>
                        <td class="is-center"><a href="/user/{{ eachuser.username }}/make_admin"><span class="d-icon d-check-circle is-small is-blue-500"></span></a></td>
                        <td class="is-center"><a href="/user/{{ eachuser.username }}/reject_request"><span class="d-icon d-decline is-small is-red-500"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    </div>

{% endblock %}

myflask/templates/countrylist.html
<option value="Afghanistan">Afghanistan</option>
<option value="Åland Islands">Åland Islands</option>
<option value="Albania">Albania</option>
<option value="Algeria">Algeria</option>
<option value="American Samoa">American Samoa</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antarctica">Antarctica</option>
<option value="Antigua and Barbuda">Antigua and Barbuda</option>
<option value="Argentina">Argentina</option>
<option value="Armenia">Armenia</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Australia</option>
<option value="Austria">Austria</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahrain</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivia</option>
<option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
<option value="Botswana">Botswana</option>
<option value="Bouvet Island">Bouvet Island</option>
<option value="Brazil">Brazil</option>
<option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
<option value="Brunei Darussalam">Brunei Darussalam</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodia</option>
<option value="Cameroon">Cameroon</option>
<option value="Canada">Canada</option>
<option value="Cape Verde">Cape Verde</option>
<option value="Cayman Islands">Cayman Islands</option>
<option value="Central African Republic">Central African Republic</option>
<option value="Chad">Chad</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Christmas Island">Christmas Island</option>
<option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
<option value="Colombia">Colombia</option>
<option value="Comoros">Comoros</option>
<option value="Congo">Congo</option>
<option value="Congo, The Democratic Republic of The">Congo, The Democratic Republic of
    The
</option>
<option value="Cook Islands">Cook Islands</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Cote D'ivoire">Cote D'ivoire</option>
<option value="Croatia">Croatia</option>
<option value="Cuba">Cuba</option>
<option value="Cyprus">Cyprus</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Denmark">Denmark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominica</option>
<option value="Dominican Republic">Dominican Republic</option>
<option value="Ecuador">Ecuador</option>
<option value="Egypt">Egypt</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Equatorial Guinea</option>
<option value="Eritrea">Eritrea</option>
<option value="Estonia">Estonia</option>
<option value="Ethiopia">Ethiopia</option>
<option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
<option value="Faroe Islands">Faroe Islands</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finland</option>
<option value="France">France</option>
<option value="French Guiana">French Guiana</option>
<option value="French Polynesia">French Polynesia</option>
<option value="French Southern Territories">French Southern Territories</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambia</option>
<option value="Georgia">Georgia</option>
<option value="Germany">Germany</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Greece">Greece</option>
<option value="Greenland">Greenland</option>
<option value="Grenada">Grenada</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guernsey">Guernsey</option>
<option value="Guinea">Guinea</option>
<option value="Guinea-bissau">Guinea-bissau</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands
</option>
<option value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Hungary</option>
<option value="Iceland">Iceland</option>
<option value="India">India</option>
<option value="Indonesia">Indonesia</option>
<option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Ireland</option>
<option value="Isle of Man">Isle of Man</option>
<option value="Israel">Israel</option>
<option value="Italy">Italy</option>
<option value="Jamaica">Jamaica</option>
<option value="Japan">Japan</option>
<option value="Jersey">Jersey</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea, Democratic People's Republic of">Korea, Democratic People's
    Republic of
</option>
<option value="Korea, Republic of">Korea, Republic of</option>
<option value="Kuwait">Kuwait</option>
<option value="Kyrgyzstan">Kyrgyzstan</option>
<option value="Lao People's Democratic Republic">Lao People's Democratic Republic
</option>
<option value="Latvia">Latvia</option>
<option value="Lebanon">Lebanon</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberia</option>
<option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lithuania</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macao">Macao</option>
<option value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former
    Yugoslav
    Republic of
</option>
<option value="Madagascar">Madagascar</option>
<option value="Malawi">Malawi</option>
<option value="Malaysia">Malaysia</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marshall Islands">Marshall Islands</option>
<option value="Martinique">Martinique</option>
<option value="Mauritania">Mauritania</option>
<option value="Mauritius">Mauritius</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Mexico</option>
<option value="Micronesia, Federated States of">Micronesia, Federated States of</option>
<option value="Moldova, Republic of">Moldova, Republic of</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolia</option>
<option value="Montenegro">Montenegro</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Morocco</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Namibia">Namibia</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Netherlands">Netherlands</option>
<option value="Netherlands Antilles">Netherlands Antilles</option>
<option value="New Caledonia">New Caledonia</option>
<option value="New Zealand">New Zealand</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Niue</option>
<option value="Norfolk Island">Norfolk Island</option>
<option value="Northern Mariana Islands">Northern Mariana Islands</option>
<option value="Norway">Norway</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau">Palau</option>
<option value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua New Guinea</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="Philippines">Philippines</option>
<option value="Pitcairn">Pitcairn</option>
<option value="Poland">Poland</option>
<option value="Portugal">Portugal</option>
<option value="Puerto Rico">Puerto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Reunion">Reunion</option>
<option value="Romania">Romania</option>
<option value="Russian Federation">Russian Federation</option>
<option value="Rwanda">Rwanda</option>
<option value="Saint Helena">Saint Helena</option>
<option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
<option value="Saint Lucia">Saint Lucia</option>
<option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
<option value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines
</option>
<option value="Samoa">Samoa</option>
<option value="San Marino">San Marino</option>
<option value="Sao Tome and Principe">Sao Tome and Principe</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Senegal">Senegal</option>
<option value="Serbia">Serbia</option>
<option value="Seychelles">Seychelles</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovakia</option>
<option value="Slovenia">Slovenia</option>
<option value="Solomon Islands">Solomon Islands</option>
<option value="Somalia">Somalia</option>
<option value="South Africa">South Africa</option>
<option value="South Georgia and The South Sandwich Islands">South Georgia and The South
    Sandwich Islands
</option>
<option value="Spain">Spain</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Sudan</option>
<option value="Suriname">Suriname</option>
<option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Sweden</option>
<option value="Switzerland">Switzerland</option>
<option value="Syrian Arab Republic">Syrian Arab Republic</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
<option value="Thailand">Thailand</option>
<option value="Timor-leste">Timor-leste</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad and Tobago">Trinidad and Tobago</option>
<option value="Tunisia">Tunisia</option>
<option value="Turkey">Turkey</option>
<option value="Turkmenistan">Turkmenistan</option>
<option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Emirates">United Arab Emirates</option>
<option value="United Kingdom">United Kingdom</option>
<option value="United States">United States</option>
<option value="United States Minor Outlying Islands">United States Minor Outlying
    Islands
</option>
<option value="Uruguay">Uruguay</option>
<option value="Uzbekistan">Uzbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Venezuela">Venezuela</option>
<option value="Viet Nam">Viet Nam</option>
<option value="Virgin Islands, British">Virgin Islands, British</option>
<option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
<option value="Wallis and Futuna">Wallis and Futuna</option>
<option value="Western Sahara">Western Sahara</option>
<option value="Yemen">Yemen</option>
<option value="Zambia">Zambia</option>
<option value="Zimbabwe">Zimbabwe</option>

myflask/templates/flashmessages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
        <div class="alert is-inline has-bg-{{ category }}">
            <p class="is-bold">{{ message }}</p>
        </div>
    {% endfor %}
{% endwith %}

myflask/templates/for_countries.html
{% extends 'layout.html' %}
{% set page_name = 'for_countries' %}
{% block content %}
    {% include 'flashmessages.html' %}


    <div class="flex h-minus-nav">
        {% include 'sidebar_eruptions.html' %}


        <iframe src="{{ url_for('main.dash_app3') }}" title="description" width="100%"></iframe>

    </div>
{% endblock %}

myflask/templates/index.html
{% extends 'layout.html' %}
{% set page_name = 'home' %}
{% block content %}
    {% include 'flashmessages.html' %}


    <div class="flex h-minus-nav">
        


            <iframe src="{{ url_for('main.dash_app_index') }}" title="description" width="100%"></iframe>

    </div>
{% endblock %}

myflask/templates/login.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% set page_name = 'login' %}
{% block content %}
    {% include 'flashmessages.html' %}

    <div class="flex h-minus-nav">
        {%  include 'sidebar_auth.html' %}

        <div class="overflow-y-auto flex-auto">
            <div class="container-full m-t-30 m-b-40">
                <h2>Login</h2>

                <br>
                <form method=post action="{{ url_for('auth.login') }}">

                    {{ form.csrf_token }}
                    {{ render_field(form.username) }}
                    {{ render_field(form.password) }}
                    <div>
                        <input id="remember" name="remember" type="checkbox" value="value1"/>
                        <label for="remember">{{ form.remember.label }}</label>
                    </div>


                    <div class="input-group responsive m-t-40">
                        <button class="button is-solid m-r-10" type="submit" value="Login">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



{% endblock %}

myflask/templates/navbar.html
<nav class="nav">
    <div class="nav-left">

        <img class="nav-brand" src="{{ url_for('static', filename='images/biglogo.png') }}" alt=""/>
        <div class="float-right hide-small-desktop-up">
            {% if current_user.is_anonymous %}
                <div></div>
            {% else %}
                <a class="nav-item" href="{{ url_for('main.index') }}">
                    <i class="d-icon d-home-solid"></i>
                </a>

                <div class="menu menu--nav is-right">
                    <div class="nav-item menu-trigger"
                    ><i class="d-icon d-chart-area"></i>
                    </div>
                    <div class="menu-content">
                        <a href="{{ url_for('main.eruption_numbers') }}">Volcanoes on the World Map</a>
                        <a href="{{ url_for('main.yearly_data') }}">Yearly Data</a>
                        <a href="{{ url_for('main.for_countries') }}">Data for Individual Countries</a>
                        <a href="{{ url_for('main.population') }}">Risk to the Population</a>
                    </div>
                </div>

                {% if current_user.user_type == 'admin' %}
                    <div class="menu menu--nav is-right">
                        <div class="nav-item menu-trigger"
                        ><i class="d-icon d-file-edit-solid"></i>
                        </div>
                        <div class="menu-content">
                            <a href="{{ url_for('auth.admin') }}">User Management</a>
                            <a href="{{ url_for('auth.admin_requests') }}">Admin Requests</a>
                            <a href="{{ url_for('auth.change_password') }}">New Eruptions</a>
                        </div>
                    </div>

                    <a class="nav-item is-bold is-green-500">
                        <i class="d-icon d-security-verified-solid"></i>
                    </a>
                {% elif current_user.user_type == 'A' %}
                    <a class="nav-item is-bold is-yellow-500">
                        <i class="d-icon d-security-verified-solid"></i>
                    </a>
                {% endif %}

                <div class="menu menu--nav is-right">
                    <div class="nav-item menu-trigger">
                            <i class="d-icon d-user-profile-circle"></i>
                    </div>
                    <div class="menu-content">
                        <a href="{{ url_for('auth.update') }}">Profile</a>
                        <a href="{{ url_for('auth.change_password') }}">Change Password</a>
                        <a href="{{ url_for('auth.delete_account') }}">Delete Account</a>
                        <a href="{{ url_for('auth.logout') }}">Logout</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% if current_user.is_anonymous %}
        <div></div>
    {% else %}
        <div class="nav-responsive" id="navMenuContent">
            <div class="nav-center">
                <a class="nav-item" href="{{ url_for('main.index') }}">
                    <i class="d-icon d-home-solid"></i> Home
                </a>
                <a class="nav-item" href="{{ url_for('main.eruption_numbers') }}">
                    <i class="d-icon d-chart-area"></i> Eruptions Data
                </a>
                {% if current_user.user_type == 'admin' %}
                    <a class="nav-item" href="{{ url_for('auth.admin') }}">
                        <i class="d-icon d-file-edit-solid"></i> Manage Website
                    </a>
                {% endif %}
            </div>
            <div class="nav-right">
                {% if current_user.user_type == 'admin' %}
                    <a class="nav-item is-bold is-green-500">
                        <i class="d-icon d-security-verified-solid"></i> Admin
                    </a>
                {% elif current_user.user_type == 'A' %}
                    <a class="nav-item is-bold is-yellow-500">
                        <i class="d-icon d-security-verified-solid"></i> Pending
                    </a>
                {% endif %}
                <div class="menu menu--nav is-right">
                    <div class="nav-item menu-trigger">
                            {{ current_user.first_name }} <i class="d-icon d-user-profile-circle"></i>
                    </div>
                    <div class="menu-content">
                        <a href="{{ url_for('auth.update') }}">Account Settings</a>
                        <a href="{{ url_for('auth.logout') }}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</nav>

myflask/templates/population.html
{% extends 'layout.html' %}
{% set page_name = 'population' %}
{% block content %}
    {% include 'flashmessages.html' %}


    <div class="flex h-minus-nav">
        {% include 'sidebar_eruptions.html' %}


        <iframe src="{{ url_for('main.dash_app4') }}" title="description" width="100%"></iframe>

    </div>
{% endblock %}

myflask/templates/sidebar_auth.html
<div class="tabs is-primary is-vertical hide-tablet-down">
    <ul>
        <li class={% if page_name=='login' %}"is-active"{% endif %}><a href="{{ url_for('auth.login') }}">Login</a></li>
        <li class={% if page_name=='signup' %}"is-active"{% endif %}><a href="{{ url_for('auth.signup') }}">Sign Up</a></li>
    </ul>
</div>

myflask/templates/sidebar_settings.html
<div class="tabs is-primary is-vertical hide-tablet-down">
    <ul>
        <li class={% if page_name=='profile' %}"is-active"{% endif %}>
            <a href="{{ url_for('auth.update') }}">Profile</a>
        </li>

        <li class={% if page_name=='change_password' %}"is-active"{% endif %}>
            <a href="{{ url_for('auth.change_password') }}">Change Password</a>
        </li>

        <li class={% if page_name=='delete_account' %}"is-active"{% endif %}>
            <a href="{{ url_for('auth.delete_account') }}">Delete Account</a>
        </li>
    </ul>
</div>